apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: idec
rules:
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - networking.istio.io
    resources:
      - virtualservices
      - gateways
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: idec
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: idec
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: idec
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: idec
      app.kubernetes.io/name: ingress-dns-export-controller
  template:
    metadata:
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "false"
      labels:
        app: idec
        app.kubernetes.io/component: idec
        app.kubernetes.io/instance: idec
        app.kubernetes.io/name: ingress-dns-export-controller
        app.kubernetes.io/version: 0.2.2
    spec:
      containers:
        - image: ghcr.io/joostvdg/idec:0.1.29-amd
          livenessProbe:
            failureThreshold: 6
            httpGet:
              path: /actuator/health/liveness
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 20
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          name: ingress-dns-export-controller
          ports:
            - containerPort: 8080
              protocol: TCP
          readinessProbe:
            failureThreshold: 6
            httpGet:
              path: /actuator/health/readiness
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 25
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: idec
    app.kubernetes.io/name: ingress-dns-export-controller
    app.kubernetes.io/version: 0.2.2
  name: idec
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/instance: idec
    app.kubernetes.io/name: ingress-dns-export-controller
  type: ClusterIP
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: idec
spec:
  selector:
    istio: ingressgateway
  servers:
    - hosts:
        - "*"
      port:
        name: http
        number: 80
        protocol: HTTP
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: idec
spec:
  gateways:
    - idec
  hosts:
    - idec.example.com
  http:
    - route:
        - destination:
            host: idec
            port:
              number: 80